### ISSUE TITLE
Uncaught TypeError: Cannot read property 'markers' of undefined

### ISSUE THREAD

**Issue by gangadath** [gunawanlie/atom-regex-extractor#13]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.6
**Thrown From**: [atom-regex-extractor](https://github.com/gunawanlie/atom-regex-extractor) package 0.8.2

### Stack Trace

Uncaught TypeError: Cannot read property 'markers' of undefined

```
At /Users/R01349/.atom/packages/atom-regex-extractor/lib/atom-regex-extractor.js:71

TypeError: Cannot read property 'markers' of undefined
    at Object.getResultCount (/packages/atom-regex-extractor/lib/atom-regex-extractor.js:71:53)
    at Object.extractFindResults (/packages/atom-regex-extractor/lib/atom-regex-extractor.js:37:28)
    at Object.extract (/packages/atom-regex-extractor/lib/atom-regex-extractor.js:30:22)
    at HTMLElement.atomRegexExtractorExtract (/packages/atom-regex-extractor/lib/atom-regex-extractor.js:15:50)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349780)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348255)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:725974)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:733897)
    at EventEmitter.emit (events.js:194:13)
```

### Commands

```
     -3:02.1.0 window:install-shell-commands (div.tool-panel.tree-view)
     -1:43 pane:reopen-closed-item (input.hidden-input)
     -0:59 window:toggle-dev-tools (input.hidden-input)
     -0:12.4.0 atom-regex-extractor:extract (input.hidden-input)
```

### Non-Core Packages

```
align-regexp 0.4.0 
atom-regex-extractor 0.8.2 
atom-regextoolkit 1.0.0 
color-tabs-regex 0.2.5 
demo-packege 0.1.0 
language-regexp 1.1.3 
linter-frege 1.0.0 
one-dark-regex-syntax 1.2.0 
regex-comments 2.0.0 
regex-filter-and-generator 1.4.2 
regex-railroad-diagram 0.19.4 
regex-replacer-js 0.1.0 
regex-tester 0.2.2 
reggae-syntax 0.2.0 
```

**Comment by gunawanlie** [comment]
did you follow the steps how to use this package ?
